# Generated by Codex on 2026-04-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postanalytics',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
