# Generated by Codex on 2026-04-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_alter_weeklyplan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyplan',
            name='instagram_media_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
